version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install cfn-lint
      - pip install taskcat
  pre_build:
    commands:
      - echo "Linting CloudFormation template..."
      - cfn-lint infrastructure.yaml
  build:
    commands:
      - echo "Testing with Taskcat..."
      - taskcat test run